# -*- coding: utf-8 -*-
"""LLM_Text2SQL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3jI56HxrELiBZpR4tXm2AOGHcja5YYQ
"""

import sqlite3

## Connectt to SQlite
connection=sqlite3.connect("student.db")

# Create a cursor object to insert record,create table

cursor=connection.cursor()

## create the table
table_info="""
Create table STUDENT(NAME VARCHAR(25),CLASS VARCHAR(25),
SECTION VARCHAR(25),MARKS INT);

"""
cursor.execute(table_info)

## Insert Some more records

cursor.execute('''Insert Into STUDENT values('Sunil','AI','A',95)''')
cursor.execute('''Insert Into STUDENT values('Murali','DS','B',100)''')
cursor.execute('''Insert Into STUDENT values('Krishna','AI','A',86)''')
cursor.execute('''Insert Into STUDENT values('Ravi','DEVOPS','A',50)''')
cursor.execute('''Insert Into STUDENT values('Anusha','DEVOPS','A',45)''')

## Disspaly ALl the records

print("The isnerted records are")
data=cursor.execute('''Select * from STUDENT''')
for row in data:
    print(row)

## Commit your changes int he databse
connection.commit()
connection.close()
